<div style="background-color: lightgray; padding: 18px;">
    <h1> Learning Python | Day 13
    
</div>

### Features:

- Intro to NumPy
- Installation
- Creating arrays
- Basic Properties

<div style="background-color: lightgreen; padding: 10px;">
    <h2> Intro to NumPy
</div>

***What is numpy?***

NumPy stands for *Numerical Python*.

It is a powerful math library used for working with ``arrays``.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.



***Why is NumPy Faster Than Lists?***

NumPy N-dimensional arrays (``ndarray``) are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

When we organize our code to take advantage of NumPy's operations, we commonly say that we "vectorize" our code. This means that we avoid explicit loops in Python code and rewrite everything using NumPy arrays. 

Thus, we can leverage the speed of "vectorized" operations, significantly speeding up our code.

***Which Language is NumPy written in?***

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

Sources:
- https://www.w3schools.com/python/numpy/numpy_intro.asp
- https://www.geeksforgeeks.org/introduction-to-numpy/?ref=lbp
- https://github.com/numpy/numpy?tab=readme-ov-file
- https://numpy.org/
- https://numpy.org/doc/stable/
- https://numpy.org/doc/stable/user/absolute_beginners.html
- https://numpy.org/doc/stable/reference/arrays.ndarray.html

<div style="background-color: lightgreen; padding: 10px;">
    <h2> Installation of NumPy
</div>

***Installing on cmd:***

``C:\Users\Your Name>pip install numpy``

In [3]:
# Importing in my application:
import numpy

In [4]:
# Example:

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


***NumPy is usually imported under the np alias:***

``import numpy as np``

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [6]:
# Checking version:

print(np.__version__)

1.24.3


<div style="background-color: lightgreen; padding: 10px;">
    <h2> Arrays
</div>

***Arrays in NumPy:***

``NumPy`` main object is the homogeneous multidimensional array.

- It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
- In *NumPy*, dimensions are called axes. The number of axes is rank.
- ``NumPy`` array class is called ``ndarray`` (n-dimensional array). It is also known by the alias array.

It can be a list of values, a table, or a table of tables. The important thing is that all values are of the same "type." If one of them is an ``integer``, all will be. If one of them is a ``float``, all will be. This type is called ``dtype``.

The most common usage is to use ndarrays as lists or tables of values.

Sources:
- https://www.w3schools.com/python/numpy/numpy_creating_arrays.asp
- https://www.geeksforgeeks.org/numpy-array-in-python/?ref=lbp

---

In the case of a list, we have a one-dimensional ``ndarray``. Mathematically, this object is **equivalent** to a vector.

The most common method to create an ``ndarray`` is by using the ``np.array`` function. Thus, to create our "vector," we use the following command.

In [24]:
import numpy as np

vector = np.array([1, 2, 3])
print(vector)

# If we look at the type of the variable "vetor," we will see that it is of the NumPy.ndarray type.
print(type(vector))

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
# Example ~ two-dimensional array that has the rank of 2 as it has 2 axes:

import numpy as np 
  
# Creating array object 
arr = np.array( [[ 1, 2, 3], 
                 [ 4, 2, 5]] ) 
  
# Printing type of arr object 
print("Array is of type: ", type(arr)) 
  
# Printing array dimensions (axes) 
print("No. of dimensions: ", arr.ndim) 
  
# Printing shape of array 
print("Shape of array: ", arr.shape) 
  
# Printing size (total number of elements) of array 
print("Size of array: ", arr.size) 
  
# Printing type of elements in array 
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


---

It is also possible to increase the number of dimensions.

-  In this case, if we have 3 dimensions, for example, we would have a list of tables.
-  If there are 4 dimensions, then we have a table whose elements are tables

 Thus, the more dimensions, we stack objects with fewer dimensions into a list.

 If there are 5 dimensions, we have a list of ndarrays with 4 dimensions (or a list of tables of tables).

Mathematically, when we have 3 dimensions or more, we call this object`` a ten``sor.

In [16]:
tensor = np.array([[[1, 2], [3, 4]], [[1, 0],[0, 1]]])
print(tensor)

[[[1 2]
  [3 4]]

 [[1 0]
  [0 1]]]


---
Note that the variable **"tensor"** is nothing more than two tables.

A visual representation of ``ndarrays`` can help to better understand what is happening.

<img src=https://s3-sa-east-1.amazonaws.com/lcpi/b50bd331-732b-48a4-9d46-01f20c15ab29.png width=500>

---
Furthermore, it is common to refer to each dimension of an ``ndarray`` as an "axis". Thus, if an ndarray has 3 dimensions, we can speak of the "1st dimension of the array" (axis 0 of the array), the "2nd dimension of the array" (axis 1 of the array), and the "3rd dimension of the array" (axis 2 of the array). 

Bringing some abstraction to our way of viewing the structure, an ``ndarray`` with shape (3, 3, 2) could be understood as a list along its first axis (axis 0), for example. This list would be composed of 3 matrices of size 3 x 2. Equivalently, we could think of it as a list with 2 matrices 3 x 3 along its third axis (axis 2).

<img src=https://s3-sa-east-1.amazonaws.com/lcpi/1e527c6a-ea64-46e3-bd31-ffba06749000.png width=600>

The ``ndarray`` is the basic data structure of **NumPy**, and it is the structure we will always use. All the power of NumPy comes from the implementation of this data structure and the related operations, which are much more efficient than the native operations that could apply to common Python lists.

These objects are also very common in mathematics because they basically represent **vectors and matrices**. Thus, it is straightforward to "vectorize" our code by writing it in a way that is very similar to what we would do in mathematical notation.

__Note:__ We also mentioned tensors before. It is not important to understand what they are to use NumPy. Only very specific calculations use tensor mathematics. For most cases, it is enough to have the view we provided earlier, about how they are basically "matrices with 3 or more dimensions". This means they can be a list of tables, a table of tables, a list of tables of tables, a table of tables of tables, and so on.

---
At this point, the most striking difference between ``ndarrays`` and native Python ``lists`` is **static typing**. 

In the context of ``ndarrays``, all elements of an array need to have the **same data type**.

In other words, NumPy will perform automatic coercion to ensure that all elements have the same type. In this case, all elements will be converted to strings, resulting in an ndarray of string type. You can see the general type of the data that is part of an array as follows:

In [28]:
# Example:
vector2 = np.array([3.14, 10, "Matheus", True])

In [27]:
print(vector2)
print(type(vector2[0]))
print(type(vector2[1]))
print(type(vector2[2]))
print(type(vector2[3]))

['3.14' '10' 'Matheus' 'True']
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [34]:
# Another Example:
test = np.array([1, 5, 'AAA', 10])

In [42]:
test.dtype

dtype('<U11')

In [31]:
type(test[0])

numpy.str_

In [44]:
# Last example:
test2 = np.array([10,15,20])

In [41]:
print(type(test2[0]))
print(test2.dtype)

<class 'numpy.int32'>
int32


---
**Careful**: Copying and modifying ``ndarrays``

Before we begin to explore the basic properties of an ndarray, it is important to keep a very important concept in mind. Just like native Python arrays, due to how ``NumPy`` works with ndarrays in the computer's memory, they behave as shown below:

Resource:
- https://pythontutor.com/render.html#mode=display
- https://www.dataquest.io/blog/python-copy-list/

In [1]:
a = [['A', 'B', 'C'],['1', '2', '3']]
b = a.copy()
b[0][1] = 'X'
print(a)

[['A', 'X', 'C'], ['1', '2', '3']]


In [2]:
import copy
a = [['A', 'B', 'C'],['1', '2', '3']]
b = copy.deepcopy(a)
b[0][1] = 'X'
print(a)

[['A', 'B', 'C'], ['1', '2', '3']]


In [4]:
a = [[1,2,3,4,5], [10,20,30,40,5]]
b = a.copy()

def teste(lista):
    lista[1][4] = 'X'

teste(b)
print(a)

[[1, 2, 3, 4, 5], [10, 20, 30, 40, 'X']]


In [5]:
def teste2(lista):
    x = lista.copy()
    x[1][3] = 'Y'
    return x

m = teste2(b)
print(a, m)

[[1, 2, 3, 4, 5], [10, 20, 30, 'Y', 'X']] [[1, 2, 3, 4, 5], [10, 20, 30, 'Y', 'X']]


<div style="background-color: lightgreen; padding: 10px;">
    <h2> Basic Properties
</div>

Basic properties of ``ndarrays``

*Dimension and Shape*

As we saw before, it is possible to create an ndarray with different ``dimensions`` and ``shapes``. Each ndarray has the ``ndim`` and ``shape`` attributes that store this information. Therefore, to find out the structure of our array, we just need to access these attributes.

- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr.ndim)
print(arr.shape)

print('-'*32)

mat = np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]])
print(mat.ndim)
print(mat.shape)

print('-'*32)

tensor = np.array([[[1, 2], [3, 4]], [[1, 0],[0, 1]]])
print(tensor.ndim)
print(tensor.shape)

1
(5,)
--------------------------------
2
(2, 5)
--------------------------------
3
(2, 2, 2)


---
This is extremely important to help us when we have a very large ``ndarray`` and need to recall how large it is. Additionally, these attributes also assist us when we want to create generic functions that operate on ndarrays.

From the array's shape, we can also obtain the **number of elements**. However, ndarray objects already have the ``size`` attribute to make this easier.

In [6]:
print(arr.size)
print('-'*32)

print(mat.size)
print('-'*32)

print(tensor.size)

5
--------------------------------
10
--------------------------------
8


---
Next classes:
- Data Types
- Indexing and Slicing
- Advanced Indexing | Boolean Mask
- Arithmetic Operations